services:
  nestjs:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: rest_api
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
  postgres_db:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
        - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: