services:
  rest_api:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
